<?php

namespace AmsterdamPHP\Bundle\SponsorBundle\Repository;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * PackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingPackageRepository extends EntityRepository
{
    /**
     * @param null $year
     * @return ArrayCollection
     */
    public function getRecentMeetingPackages($max = null, $year = null)
    {
        $year = $year ?: (new \DateTime('now'))->format('Y');

        $qb = $this->createQueryBuilder('meeting');
        $qb->andWhere('SUBSTRING(meeting.meetingDate, 0, 4) <= :year');
        $qb->setParameter('year', $year);

        if ($max !== null) {
            $qb->setMaxResults($max);
        }

        return new ArrayCollection($qb->getQuery()->getResult());
    }
}
