<?php

namespace AmsterdamPHP\Bundle\SponsorBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingPackageRepository extends EntityRepository
{
}
