services:

    amsterdamphp_site.integration.blog:
        class: AmsterdamPHP\Bundle\SiteBundle\Service\BlogService
        arguments:
            cache: @snc_redis.cache

    amsterdamphp_site.email.contact:
        class: AmsterdamPHP\Bundle\SiteBundle\Service\ContactService
        arguments:
            akismet: @ornicar_akismet
            mailer: @mailer
        scope: request

    amsterdamphp_site.form.contact:
        class: AmsterdamPHP\Bundle\SiteBundle\Form\ContactFormType
        tags:
            - { name: form.type, alias: "amsterdamphp_site_contact_type"}
