parameters:
    amsterdamphp_site.integration.youtube_factory.class: AmsterdamPHP\Bundle\SiteBundle\Service\YoutubeFactory
    amsterdamphp_site.integration.youtube_client.class: Madcoda\Youtube

services:
    amsterdamphp_site.integration.youtube_factory:
        class: %amsterdamphp_site.integration.youtube_factory.class%
        arguments:
            key: %youtube_key%

    amsterdamphp_site.integration.youtube_client:
        class:            "%amsterdamphp_site.integration.youtube_client.class%"
        factory_service:  amsterdamphp_site.integration.youtube_factory
        factory_method:   getClient

    amsterdamphp_site.integration.blog:
        class: AmsterdamPHP\Bundle\SiteBundle\Service\BlogService
        arguments:
            cache: @snc_redis.cache

    amsterdamphp_site.integration.youtube:
        class: AmsterdamPHP\Bundle\SiteBundle\Service\YoutubeService
        arguments:
            cache: @snc_redis.cache
            client: @amsterdamphp_site.integration.youtube_client
            playlist: %youtube_playlist%

    amsterdamphp_site.email.contact:
        class: AmsterdamPHP\Bundle\SiteBundle\Service\ContactService
        arguments:
            akismet: @ornicar_akismet
            mailer: @mailer
        scope: request

    amsterdamphp_site.form.contact:
        class: AmsterdamPHP\Bundle\SiteBundle\Form\ContactFormType
        tags:
            - { name: form.type, alias: "amsterdamphp_site_contact_type"}
