parameters:
    meetup.photos.class: AmsterdamPHP\Bundle\MeetupBundle\Service\PhotoService
    meetup.events.class: AmsterdamPHP\Bundle\MeetupBundle\Service\EventService
    meetup.sponsors.class: AmsterdamPHP\Bundle\MeetupBundle\Service\SponsorService
    meetup.twig.photos.class: AmsterdamPHP\Bundle\MeetupBundle\Twig\PhotoRenderer
services:

    meetup.photos:
        class: %meetup.photos.class%
        arguments:
            client: @dms_meetup_api.key_client
            cache: @snc_redis.cache
            group: %group_urlname%

    meetup.sponsors:
        class: %meetup.sponsors.class%
        arguments:
            client: @dms_meetup_api.key_client
            cache: @snc_redis.cache
            group: %group_urlname%

    meetup.events:
        class: %meetup.events.class%
        arguments:
            client: @dms_meetup_api.key_client
            cache: @snc_redis.cache
            group: %group_urlname%

    meetup.twig.photos:
        class: %meetup.twig.photos.class%
        arguments:
            photos: @meetup.photos
        tags:
            - { name: twig.extension }
