imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
# Bootstrap
braincrafted_bootstrap:
    assets_dir:     %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path:    %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.2.js

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    write_to:       %kernel.root_dir%/../web
    filters:
        less:
            node:       /usr/bin/node
            node_paths: [/usr/lib/node_modules]
            apply_to:   "\.less$"
        cssrewrite: ~
        uglifyjs:
            bin: /usr/local/bin/uglifyjs
        uglifycss:
            bin: /usr/local/bin/uglifycss
    assets:
        ie8:
            inputs:
                - https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js
                - https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js
            filters:
                - ?uglifyjs
            output: js/ie8.js
        amsterdamphp:
            inputs:
                - %kernel.root_dir%/Resources/less/amsterdamphp.less
            filters:
                - cssrewrite
                - ?uglifycss
            output: css/amsterdamphp.css
        amsterdamphp-js:
            inputs:
                - %kernel.root_dir%/../web/js/jquery.js
                - %kernel.root_dir%/../web/js/bootstrap.js
            filters:
                - ?uglifyjs
            output: js/amsterdamphp.js

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

dms_meetup_api:
    client:
        key: %meetup_key%

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost
        cache:
            type: predis
            alias: cache
            dsn: redis://localhost

ornicar_akismet:
    api_key:        %akismet_key%
    url:            http://amsterdamphp.nl

google:
    analytics:
        trackers:
            default:
                name:      amsphp-analytics
                accountId: ~
                domain:    amsterdamphp.nl
                trackPageLoadTime: true

liip_imagine:
    filter_sets:
        sponsor_homepage:
            quality: 100
            filters:
                thumbnail: { size: [120, 90], mode: inset }
        sponsor_bronze:
             quality: 100
             filters:
                thumbnail: { size: [155, 60], mode: inset }
        sponsor_community:
             quality: 100
             filters:
                thumbnail: { size: [53, 35], mode: inset }
