amsterdam_php_site:
    resource: "@AmsterdamPHPSiteBundle/Controller/"
    type:     annotation
    prefix:   /

amsterdam_php_sponsors:
    resource: "@AmsterdamPHPSponsorBundle/Controller/"
    type:     annotation
    prefix:   /

#amsterdam_php_meetup:
#    resource: "@AmsterdamPHPMeetupBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
