security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: $2y$12$SqGYRAIb.NiS9rsHHhpJBOUqa2bdiezVjH0lmncI1NiWtARyJZ7Jm, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login

                csrf_provider: form.csrf_provider

                username_parameter: "amsterdamphp_login[username]"
                password_parameter: "amsterdamphp_login[password]"
                use_referer: true
                target_path_parameter: "amsterdamphp_login[_target_path]"
            logout:       true
            anonymous:    ~
            remember_me:
                key: %secret%
                remember_me_parameter: "amsterdamphp_login[_remember_me]"
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
