---
- name: App | Logs folder present
  file: path={{ write_to_folder}}/logs state=directory

- name: App | Cache folder present
  file: path={{ root_folder }}/app/cache state=directory

- name: App | Folder Permissions (Part 1)
  command: sudo setfacl -R -m u:www-data:rwX -m u:vagrant:rwX {{ write_to_folder}}

- name: App | Folder Permissions (Part 2)
  command: sudo setfacl -dR -m u:www-data:rwX -m u:vagrant:rwX {{ write_to_folder}}

- name: App | Logs Folder Symlink
  file: src={{ write_to_folder }}/logs dest={{ root_folder }}/app/logs state=link

- name: App | Check parameters.yml
  action: shell test -f {{ root_folder }}/app/config/parameters.yml
  register: parameters_present

- name: App | Populate parameters.yml
  action: template src=../files/parameters.dist.yml dest={{ root_folder }}/app/config/parameters.yml
  when: parameters_present # find better way to do this

- name: App | Composer install
  command: composer install -n --no-progress chdir={{ root_folder }}

- name: App | npm install
  command: npm install chdir={{ root_folder }}
  sudo: False

- name: App | Bower install
  command: bower install chdir={{ root_folder }}
  sudo: False

#- name: App | Run Migrations
#  command: php app/console doctrine:migrations:migrate -n chdir={{ root_folder }}

- name: App | Ensure supervisor is running
  service: name=supervisor state=running

- name: App | Assetic Watch Config
  action: template src=../files/supervisord.conf dest=/etc/supervisor/conf.d/amsphp.conf

- name: App | Reload supervisor to launch processes
  command: supervisorctl reload

- name: App | Grunt
  command: grunt chdir={{ root_folder }}
  sudo: False

#- name: SSH Home | Point home directory to root directory
#  action: user name=vagrant home={{ root_folder }}
