---
# Development related tasks

# Apache
- name: Apache
  apt: pkg=apache2 state=installed

- name: Apache | Stop for user/group change
  service: name=apache2 state=stopped

- name: Apache | Define envvars
  template: src=../files/apache/envvars.template dest=/etc/apache2/envvars

- name: Apache | Changing lock file owner/group
  file: path=/var/lock/apache2 owner={{ apache_user }} group={{ apache_group }}

- name: Apache | Stop for user/group change
  service: name=apache2 state=started

- name: Apache Modules
  command: a2enmod {{ item }}
  notify: restart apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter

# Storage
- name: MySQL
  apt: pkg=mysql-server state=installed

- name: MySQL
  apt: pkg=python-mysqldb state=installed

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: MySQL | Set Root Password
  mysql_user: name={{ dbuser }} host={{ item }} password={{ dbpasswd }} priv=*.*:ALL,GRANT
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: MySQL | Copy Config File
  template: src=../files/.my.cnf dest=/{{ dbuser }}/.my.cnf owner={{ dbuser }} mode=0600

- name: MySQL | Create App DB
  mysql_db: name={{ dbname }} state=present login_password={{ dbpasswd }} login_user={{ dbuser }}

- name: Redis
  apt: pkg=redis-server state=installed

# PHP
- name: PHP 5.5 Custom Repo
  apt_repository: repo='ppa:ondrej/php5' update_cache=yes

- name: PHP and Modules
  apt: pkg={{ item }} state=latest
  notify: restart apache
  tags: common
  with_items:
    - php5
    - php5-mysql
    - php5-xmlrpc
    - php-soap
    - php5-gd
    - php-apc
    - php5-curl
    - php5-intl
    - php5-memcached
    - php5-xdebug
    - libapache2-mod-php5

# Configurations

- name: PHP | Config timezone
  ini_file: dest=/etc/php5/mods-available/timezone.ini section=Date option=date.timezone value=Europe/Amsterdam
  notify:
    - restart apache

- name: PHP | Config Memory Limit
  ini_file: dest=/etc/php5/cli/php.ini section=global option=memory_limit value=256M mode=0644
  notify:
    - restart apache

- name: PHP | Enable Custom Config
  shell: php5enmod -s ALL timezone

# Build tools

- name: Tools | nodejs
  apt: pkg=nodejs-legacy state=latest

- name: Tools | NPM
  apt: pkg=npm state=latest

- name: Tools | Modules via NPM
  npm: name={{ item }} global=yes
  with_items:
    - uglifycss
    - uglify-js
    - less
    - yo
    - bower
    - grunt-cli

- name: Tools | RubyGems
  apt: pkg=rubygems-integration state=installed

# PHP Tools

- name: Composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
