---
# Development related tasks

# Apache
- name: Apache
  action: apt pkg=apache2 state=installed

- name: Apache Modules
  action: command a2enmod $item
  notify: restart apache
  with_items:
    - rewrite 
    - vhost_alias
    - headers
    - expires
    - filter

# Storage
- name: MySQL
  action: apt pkg=mysql-server state=installed

- name: Redis
  action: apt pkg=redis-server state=installed

# PHP
- name: PHP 5.5 Custom Repo
  apt_repository: repo='ppa:ondrej/php5' update_cache=yes

- name: PHP and Modules
  action: apt pkg=$item state=latest
  notify: restart apache
  tags: common
  with_items:
    - php5
    - php5-mysql
    - php5-xmlrpc
    - php-soap
    - php5-gd
    - php-apc
    - php5-curl
    - php5-intl
    - php5-memcached

# Configurations

- name: PHP | Config timezone
  action: ini_file dest=/etc/php5/mods-available/timezone.ini section=Date option=date.timezone value=Europe/Amsterdam
  notify:
    - restart apache

# Currently PHP has a bug that adds a space that breaks ini parsing, it has been fixed, but we need to wait for 
# PHP 5.5.6 to fix this

# - name: PHP | Config Memory Limit
#   action: ini_file dest=/etc/php5/cli/php.ini section=global option=memory_limit value=256M mode=0600
#   notify:
#     - restart apache

# - name: PHP | Config Memory Limit
#   action: ini_file dest=/etc/php5/apache2/php.ini section=global option=memory_limit value=256M mode=0600
#   notify:
#     - restart apache

- name: PHP | Enable Custom Config
  action: shell php5enmod -s ALL timezone.ini 

# PHP Tools

- name: Composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer