---
- name: Apache | Copy Host Config
  template: src=../files/apache/amsphp-vhost.conf dest=/etc/apache2/sites-available/amsphp-vhost.conf

- name: Apache | Enable Host Config
  command: a2ensite amsphp-vhost.conf
  notify: restart apache

- name: Apache | Disable Default Host Config
  command: a2dissite default
  ignore_errors: true
  notify: restart apache

- name: Apache | Disable Default Host Config
  command: a2dissite 000-default.conf
  ignore_errors: true
  notify: restart apache

- name: Apache | Ensure application files are present
  file: path={{ document_root }} state=directory
