# Following instructions at: https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04

- name: Swap | Allocate file
  command: fallocate -l 2G {{ swap_file_path }}
  args:
    creates: "{{ swap_file_path }}"

- name: Swap | Set permissions
  file: path={{ swap_file_path }} mode=0600

- name: Swap | Check swap file type
  command: file {{ swap_file_path }}
  register: swapfile

- name: Swap | Set swapspace
  command: mkswap {{ swap_file_path }}
  when: swapfile.stdout.find('swap file') == -1

- name: Swap | Activate
  command: swapon {{ swap_file_path }}
  when: ansible_swaptotal_mb < 1

- name: Swap | Add to fstab
  mount: name=none
         src={{ swap_file_path }}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
