---
- hosts: all
  sudo: true
  vars:
    root_folder: /var/www/amsphp
    document_root: "{{ root_folder }}/web/"
    write_to_folder: /dev/shm
    dbname: amsphp
    dbuser: root
    dbpasswd: root
    apache_user: vagrant
  tasks:
    - include: tasks/common.yml
    - include: tasks/build.yml
    - include: tasks/development.yml
    - include: tasks/host.yml
    - include: tasks/app.yml

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

    - name: restart supervisor
      service: name=supervisord state=restarted

    - name: reload supervisor
      command: supervisorctl reload

