---
- hosts: all
  sudo: true
  vars:
    root_folder: /var/www/amsphp
    document_root: "{{ root_folder }}/web/"
  tasks:
    - include: tasks/common.yml
    - include: tasks/development.yml
    - include: tasks/host.yml
    - include: tasks/app.yml

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted